const wordsData = [
    // Food
    { word: "pizza", hint: "An Italian dish with a savory topping on a bread base" },
    { word: "sushi", hint: "Japanese dish consisting of small balls or rolls of vinegar-flavored cold rice served with a garnish of raw fish, vegetables, or egg" },
    { word: "burger", hint: "A flat round cake of minced beef that is fried or grilled and typically served in a bun or roll with various condiments and toppings" },
    { word: "pancake", hint: "A thin, flat cake of batter, usually fried and turned in a pan" },
    { word: "pasta", hint: "Italian dish consisting of dough made from durum wheat and water, extruded or stamped into various shapes and typically cooked in boiling water" },
    { word: "salad", hint: "A cold dish of various mixtures of raw or cooked vegetables, usually seasoned with oil, vinegar, or other dressing" },
    { word: "icecream", hint: "A sweetened frozen food typically eaten as a snack or dessert" },
    { word: "steak", hint: "A thick slice of meat, especially beef, cooked by broiling, frying, or other rapid methods" },
    { word: "sandwich", hint: "An item of food consisting of two pieces of bread with a filling between them" },
    { word: "cookie", hint: "A sweet baked food that is usually small, flat, and round and is made from flour and sugar" },
    { word: "chocolate", hint: "A food preparation in the form of a paste or solid block made from roasted and ground cacao seeds, typically sweetened" },
    { word: "coffee", hint: "A dark, bitter, hot beverage prepared from the roasted and ground seeds of a tropical plant" },

    // Animals
    { word: "elephant", hint: "A large herbivorous mammal with a trunk and tusks, native to Africa and Asia" },
    { word: "tiger", hint: "A large carnivorous feline mammal with a yellowish-brown coat striped with black, native to Asia" },
    { word: "giraffe", hint: "A tall African mammal with a long neck and legs, the largest ruminant and the tallest land animal" },
    { word: "penguin", hint: "A flightless seabird of the southern hemisphere, with black upper parts and white underparts and wings developed into flippers for swimming" },
    { word: "koala", hint: "An arboreal herbivorous marsupial native to Australia, with thick gray fur, large ears, and a spoon-shaped nose" },
    { word: "zebra", hint: "An African wild horse with black-and-white stripes and an erect mane" },
    { word: "whale", hint: "A very large marine mammal with a streamlined hairless body, horizontal tail fin, and a blowhole on top of the head for breathing" },
    { word: "panda", hint: "A large bearlike mammal with characteristic black-and-white markings, native to certain mountain forests of central and western China" },
    { word: "cheetah", hint: "A large slender-bodied fast-running African wild cat with a spotted coat and nonretractile claws" },
    { word: "turtle", hint: "A slow-moving reptile with a shell into which it can retract its head and thick, heavy skin" },

    // Countries
    { word: "france", hint: "A country in Western Europe known for its cuisine, art, and culture" },
    { word: "japan", hint: "An island country in East Asia known for its traditional arts, cuisine, and technology" },
    { word: "canada", hint: "A country in North America known for its vast wilderness, multicultural cities, and hockey" },
    { word: "brazil", hint: "A country in South America known for its Amazon rainforest, football (soccer), and Carnival festival" },
    { word: "india", hint: "A country in South Asia known for its diverse culture, religions, and cuisine, including curry dishes" },
    { word: "egypt", hint: "A country linking northeast Africa with the Middle East, famous for its ancient civilization and iconic monuments like the pyramids" },
    { word: "australia", hint: "A country and continent surrounded by the Indian and Pacific oceans, known for its beaches, deserts, and unique wildlife" },
    { word: "germany", hint: "A country in central Europe known for its historic landmarks, beer, and automotive industry" },
    { word: "mexico", hint: "A country in North America known for its rich cultural heritage, ancient civilizations, and spicy cuisine" },
    { word: "russia", hint: "The largest country in the world, spanning eastern Europe and northern Asia, known for its vast landscapes and history" },

    // Professions
    { word: "doctor", hint: "A person who is qualified to treat people who are ill or injured" },
    { word: "teacher", hint: "A person who teaches students in a school" },
    { word: "engineer", hint: "A person who designs, builds, or maintains engines, machines, or public works" },
    { word: "artist", hint: "A person who creates art, especially paintings or sculptures" },
    { word: "musician", hint: "A person who plays a musical instrument or sings, especially as a profession or for entertainment" },
    { word: "chef", hint: "A professional cook, typically the chief cook in a restaurant or hotel" },
    { word: "pilot", hint: "A person who operates the controls of an aircraft, especially as a profession" },
    { word: "scientist", hint: "A person who conducts scientific research to advance knowledge in an area of interest" },
    { word: "journalist", hint: "A person who writes for newspapers, magazines, or news websites, or prepares news to be broadcast" },
    { word: "lawyer", hint: "A person who practices or studies law, especially as an attorney or counselor" },

    // Technology
    { word: "computer", hint: "An electronic device for storing and processing data, typically in binary form, according to instructions given to it in a variable program" },
    { word: "internet", hint: "A global computer network providing a variety of information and communication facilities, consisting of interconnected networks using standardized communication protocols" },
    { word: "smartphone", hint: "A mobile phone with advanced features beyond traditional telephony, such as internet access and applications" },
    { word: "algorithm", hint: "A process or set of rules to be followed in calculations or other problem-solving operations, especially by a computer" },
    { word: "database", hint: "A structured set of data held in a computer, especially one that is accessible in various ways" },
    { word: "software", hint: "The programs and other operating information used by a computer" },
    { word: "robot", hint: "A machine capable of carrying out a complex series of actions automatically, especially one programmable by a computer" },
    { word: "coding", hint: "The process of assigning a code to something for the purposes of classification or identification" },
    { word: "virtual", hint: "Existing or occurring on computers or on the internet" },
    { word: "gadget", hint: "A small mechanical or electronic device or tool, especially an ingenious or novel one" },

    // Nature
    { word: "mountain", hint: "A large natural elevation of the earth's surface rising abruptly from the surrounding level; a large steep hill" },
    { word: "river", hint: "A large natural stream of water flowing in a channel to the sea, a lake, or another such stream" },
    { word: "forest", hint: "A large area covered chiefly with trees and undergrowth" },
    { word: "ocean", hint: "A very large expanse of sea, in particular, each of the main areas into which the sea is divided geographically" },
    { word: "desert", hint: "A barren area of landscape where little precipitation occurs and consequently, living conditions are hostile for plant and animal life" },
    { word: "volcano", hint: "A mountain or hill, typically conical, having a crater or vent through which lava, rock fragments, hot vapor, and gas are or have been erupted" },
    { word: "rainbow", hint: "An arc of colors formed in the sky opposite the sun by the refraction and reflection of the sun's rays in rain or mist" },
    { word: "island", hint: "A piece of land surrounded by water" },
    { word: "cave", hint: "A large underground chamber, typically of natural origin, in a hillside or cliff" },
    { word: "flower", hint: "The seed-bearing part of a plant, consisting of reproductive organs that are typically surrounded by a brightly colored corolla" },

    // Random
    { word: "unicorn", hint: "A mythical animal typically represented as a horse with a single straight horn projecting from its forehead" },
    { word: "castle", hint: "A large fortified building or group of buildings with thick walls, usually dominating the surrounding country" },
    { word: "planet", hint: "A celestial body moving in an elliptical orbit around a star" },
    { word: "treasure", hint: "A quantity of precious metals, gems, or other valuable objects" },
    { word: "mystery", hint: "Something that is difficult or impossible to understand or explain" },
    { word: "adventure", hint: "An unusual and exciting or daring experience" },
    { word: "fantasy", hint: "A genre of imaginative fiction involving magic and adventure, especially in a setting other than the real world" },
    { word: "journey", hint: "An act of traveling from one place to another" },
    { word: "legend", hint: "A traditional story sometimes popularly regarded as historical but unauthenticated" },
    { word: "mythology", hint: "A collection of myths, especially one belonging to a particular religious or cultural tradition" },
    { word: "wonder", hint: "A feeling of surprise mingled with admiration, caused by something beautiful, unexpected, unfamiliar, or inexplicable" },
    { word: "celebrate", hint: "To observe an event with ceremonies of respect, festivity, or rejoicing" }
];